In [ ]:
import pandas as pd 
pd.set_option('display.max_columns', None)

In [ ]:
# Load the dataset
app = pd.read_csv(r"C:\Users\Admin\Downloads\final_dataprep\dseb63_final_project_DP_dataset\dseb63_application_test.csv")

In [ ]:
# Check overall info
app.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246009 entries, 0 to 246008
Columns: 123 entries, Unnamed: 0 to SK_ID_CURR
dtypes: float64(65), int64(42), object(16)
memory usage: 230.9+ MB

In [ ]:
# Drop the index column
app.drop(columns = 'Unnamed: 0', inplace = True)

In [ ]:
# Check for null values
null_counts = app.isnull().sum()
print(null_counts.iloc[:50])  # First 50 columns
print(null_counts.iloc[50:100])  # Next 50 columns

TARGET                              0
NAME_CONTRACT_TYPE                  0
CODE_GENDER                         0
FLAG_OWN_CAR                        0
FLAG_OWN_REALTY                     0
CNT_CHILDREN                        0
AMT_INCOME_TOTAL                    0
AMT_CREDIT                          0
AMT_ANNUITY                        10
AMT_GOODS_PRICE                   224
NAME_TYPE_SUITE                  1046
NAME_INCOME_TYPE                    0
NAME_EDUCATION_TYPE                 0
NAME_FAMILY_STATUS                  0
NAME_HOUSING_TYPE                   0
REGION_POPULATION_RELATIVE          0
DAYS_BIRTH                          0
DAYS_EMPLOYED                       0
DAYS_REGISTRATION                   0
DAYS_ID_PUBLISH                     0
OWN_CAR_AGE                    162188
FLAG_MOBIL                          0
FLAG_EMP_PHONE                      0
FLAG_WORK_PHONE                     0
FLAG_CONT_MOBILE                    0
FLAG_PHONE                          0
FLAG_EMAIL                          0
OCCUPATION_TYPE                 77106
CNT_FAM_MEMBERS                     1
REGION_RATING_CLIENT                0
REGION_RATING_CLIENT_W_CITY         0
WEEKDAY_APPR_PROCESS_START          0
HOUR_APPR_PROCESS_START             0
REG_REGION_NOT_LIVE_REGION          0
REG_REGION_NOT_WORK_REGION          0
LIVE_REGION_NOT_WORK_REGION         0
REG_CITY_NOT_LIVE_CITY              0
REG_CITY_NOT_WORK_CITY              0
LIVE_CITY_NOT_WORK_CITY             0
ORGANIZATION_TYPE                   0
EXT_SOURCE_1                   138525
EXT_SOURCE_2                      529
EXT_SOURCE_3                    48824
APARTMENTS_AVG                 124984
BASEMENTAREA_AVG               144016
YEARS_BEGINEXPLUATATION_AVG    120082
YEARS_BUILD_AVG                163684
COMMONAREA_AVG                 171930
ELEVATORS_AVG                  131209
ENTRANCES_AVG                  123949
dtype: int64
FLOORSMAX_AVG                   122533
FLOORSMIN_AVG                   166955
LANDAREA_AVG                    146130
LIVINGAPARTMENTS_AVG            168197
LIVINGAREA_AVG                  123588
NONLIVINGAPARTMENTS_AVG         170869
NONLIVINGAREA_AVG               135944
APARTMENTS_MODE                 124984
BASEMENTAREA_MODE               144016
YEARS_BEGINEXPLUATATION_MODE    120082
YEARS_BUILD_MODE                163684
COMMONAREA_MODE                 171930
ELEVATORS_MODE                  131209
ENTRANCES_MODE                  123949
FLOORSMAX_MODE                  122533
FLOORSMIN_MODE                  166955
LANDAREA_MODE                   146130
LIVINGAPARTMENTS_MODE           168197
LIVINGAREA_MODE                 123588
NONLIVINGAPARTMENTS_MODE        170869
NONLIVINGAREA_MODE              135944
APARTMENTS_MEDI                 124984
BASEMENTAREA_MEDI               144016
YEARS_BEGINEXPLUATATION_MEDI    120082
YEARS_BUILD_MEDI                163684
COMMONAREA_MEDI                 171930
ELEVATORS_MEDI                  131209
ENTRANCES_MEDI                  123949
FLOORSMAX_MEDI                  122533
FLOORSMIN_MEDI                  166955
LANDAREA_MEDI                   146130
LIVINGAPARTMENTS_MEDI           168197
LIVINGAREA_MEDI                 123588
NONLIVINGAPARTMENTS_MEDI        170869
NONLIVINGAREA_MEDI              135944
FONDKAPREMONT_MODE              168287
HOUSETYPE_MODE                  123540
TOTALAREA_MODE                  118819
WALLSMATERIAL_MODE              125180
EMERGENCYSTATE_MODE             116692
OBS_30_CNT_SOCIAL_CIRCLE           805
DEF_30_CNT_SOCIAL_CIRCLE           805
OBS_60_CNT_SOCIAL_CIRCLE           805
DEF_60_CNT_SOCIAL_CIRCLE           805
DAYS_LAST_PHONE_CHANGE               1
FLAG_DOCUMENT_2                      0
FLAG_DOCUMENT_3                      0
FLAG_DOCUMENT_4                      0
FLAG_DOCUMENT_5                      0
FLAG_DOCUMENT_6                      0
dtype: int64

## Cleaning AMT_ANNUITY column

In [7]:
app[app['AMT_ANNUITY'].isna()]

,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_CURR
37959,0,Cash loans,M,N,N,0,180000.0,450000.0,NaN,450000.0,Unaccompanied,Commercial associate,Incomplete higher,Single / not married,House / apartment,0.026392,-10668,-2523,-4946.0,-3238,NaN,1,1,1,1,1,0,High skill tech staff,1.0,2,2,WEDNESDAY,13,0,0,0,0,0,0,Business Entity Type 3,NaN,0.626896,0.372334,0.0124,NaN,0.9662,NaN,NaN,0.00,0.0345,0.0417,NaN,NaN,NaN,0.0115,NaN,0.0000,0.0126,NaN,0.9662,NaN,NaN,0.0000,0.0345,0.0417,NaN,NaN,NaN,0.0119,NaN,0.0000,0.0125,NaN,0.9662,NaN,NaN,0.00,0.0345,0.0417,NaN,NaN,NaN,0.0117,NaN,0.0000,NaN,block of flats,0.0090,"Stone, brick",No,1.0,0.0,1.0,0.0,-2.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0,193746
39959,0,Cash loans,F,N,N,0,94500.0,450000.0,NaN,450000.0,Unaccompanied,Working,Lower secondary,Civil marriage,House / apartment,0.035792,-9027,-1270,-3640.0,-741,NaN,1,1,1,1,0,0,Laborers,2.0,2,2,MONDAY,20,0,0,0,0,0,0,Business Entity Type 1,NaN,0.727274,0.468660,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-706.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0,293488
41211,0,Cash loans,F,N,N,0,202500.0,539100.0,NaN,450000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.046220,-17376,-3950,-11524.0,-831,NaN,1,1,0,1,0,0,Cooking staff,2.0,1,1,WEDNESDAY,15,0,0,0,1,1,1,Self-employed,0.885980,0.738370,0.452534,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,-199.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0,279605
43978,0,Cash loans,F,N,N,0,162000.0,296280.0,NaN,225000.0,Unaccompanied,State servant,Higher education,Married,House / apartment,0.035792,-11329,-2040,-3195.0,-3069,NaN,1,1,0,1,0,0,Core staff,2.0,2,2,FRIDAY,13,0,0,0,1,1,1,Government,0.336803,0.566316,0.220095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-2841.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,4.0,138960
47940,0,Cash loans,M,Y,N,0,202500.0,360000.0,NaN,360000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.046220,-19762,-2498,-11285.0,-3305,4.0,1,1,1,1,1,0,Laborers,1.0,1,1,FRIDAY,15,0,1,1,0,1,1,Other,0.647350,0.583947,0.177704,0.0856,NaN,0.9841,NaN,NaN,0.08,0.0345,0.4583,NaN,NaN,NaN,0.0548,NaN,0.1139,0.0872,NaN,0.9841,NaN,NaN,0.0806,0.0345,0.4583,NaN,NaN,NaN,0.0571,NaN,0.1206,0.0864,NaN,0.9841,NaN,NaN,0.08,0.0345,0.4583,NaN,NaN,NaN,0.0558,NaN,0.1163,NaN,block of flats,0.0679,"Stone, brick",No,0.0,0.0,0.0,0.0,-743.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,1.0,0.0,0.0,6.0,280780
60698,0,Cash loans,M,Y,N,0,144000.0,219249.0,NaN,166500.0,Unaccompanied,Working,Higher education,Single / not married,Rented apartment,0.022800,-20831,-2450,-771.0,-4203,8.0,1,1,0,1,0,0,Drivers,1.0,2,2,FRIDAY,15,0,0,0,0,0,0,Business Entity Type 3,0.339389,0.667564,0.425893,0.0928,0.0719,0.9831,0.7688,0.0113,0.00,0.2069,0.1667,0.0417,0.6932,0.0748,0.0865,0.0039,0.0031,0.0945,0.0746,0.9831,0.7779,0.0114,0.0000,0.2069,0.1667,0.0417,0.7091,0.0817,0.0901,0.0039,0.0033,0.0937,0.0719,0.9831,0.7719,0.0113,0.00,0.2069,0.1667,0.0417,0.7053,0.0761,0.0880,0.0039,0.0032,not specified,block of flats,0.0687,Panel,No,0.0,0.0,0.0,0.0,-1986.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,11.0,300204
71475,0,Cash loans,F,Y,N,0,90000.0,157500.0,NaN,157500.0,Unaccompanied,State servant,Secondary / secondary special,Married,House / apartment,0.015221,-12134,-3721,-858.0,-591,2.0,1,1,0,1,1,0,Medicine staff,2.0,2,2,WEDNESDAY,11,0,0,0,0,0,0,Medicine,0.682126,0.154811,0.297087,0.1227,NaN,0.9781,NaN,NaN,0.00,0.2759,0.1667,NaN,NaN,NaN,0.1131,NaN,0.0044,0.1250,NaN,0.9782,NaN,NaN,0.0000,0.2759,0.1667,NaN,NaN,NaN,0.1178,NaN,0.0046,0.1239,NaN,0.9781,NaN,NaN,0.00,0.2759,0.1667,NaN,NaN,NaN,0.1151,NaN,0.0045,NaN,block of flats,0.1218,Panel,No,0.0,0.0,0.0,0.0,-348.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,0.0,283175
99054,0,Cash loans,F,N,Y,0,202500.0,929088.0,NaN,720000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.019689,-13902,-3540,-168.0,-4250,NaN,1,1,0,1,0,1,Secretaries,2.0,2,2,SATURDAY,12,0,0,0,0,0,0,Self-employed,0.400723,0.510934,0.581484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1331.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,5.0,147383
191407,0,Cash loans,F,N,Y,0,157500.0,792000.0,NaN,792000.0,Family,State servant,Secondary / secondary special,Married,House / apartment,0.026392,-17661,-2885,-8594.0,-1221,NaN,1,1,0,1,1,0,Managers,2.0,2,2,SATURDAY,14,0,0,0,0,0,0,Other,0.775404,0.656305,0.651260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-322.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0,87693
193396,0,Cash loans,F,N,N,0,315000.0,1483231.5,NaN,1354500.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.072508,-15072,-152,-7576.0,-4389,NaN,1,1,1,1,1,0,Accountants,2.0,1,1,WEDNESDAY,15,0,1,1,0,1,1,Self-employed,0.593394,0.267269,NaN,0.3691,0.1891,0.9806,0.7348,0.2590,0.52,0.2241,0.5417,0.5833,0.0000,0.3009,0.3756,0.0000,0.2002,0.2216,0.1435,0.9796,0.7321,0.1590,0.3222,0.1379,0.5417,0.5833,0.0000,0.1938,0.2268,0.0000,0.0720,0.3726,0.1891,0.9806,0.7383,0.2607,0.52,0.2241,0.5417,0.5833,0.0000,0.3061,0.3824,0.0000,0.2044,reg oper spec account,block of flats,0.1860,"Stone, brick",No,0.0,0.0,0.0,0.0,-504.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,689

### In all rows that this column is NaN, the result shows that the contract type is “Cash loans”. Therefore, we fillna in this column with the AMT_CREDIT divided by the average months of all the customers requiring “Cash loans”

In [ ]:
# Filter "Cash loans" customers
cash_loans = app[app['NAME_CONTRACT_TYPE'] == 'Cash loans']

# Remove NaN in AMT_CREDIT and AMT_ANNUITY
cash_loans_filtered = cash_loans.dropna(subset=['AMT_CREDIT', 'AMT_ANNUITY'])

# Calculate the average months
cash_loans_filtered['MONTHS'] = cash_loans_filtered['AMT_CREDIT'] / cash_loans_filtered['AMT_ANNUITY']
average_months = cash_loans_filtered['MONTHS'].mean()

print(f"Số tháng trung bình cho hợp đồng 'Cash loans': {average_months:.2f}")

Số tháng trung bình cho hợp đồng 'Cash loans': 21.79

C:\Users\Admin\AppData\Local\Temp\ipykernel_20936\756088765.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cash_loans_filtered['MONTHS'] = cash_loans_filtered['AMT_CREDIT'] / cash_loans_filtered['AMT_ANNUITY']

In [ ]:
# Fill the NaN value in AMT_ANNUITY
avg_months = average_months 
app['AMT_ANNUITY'] = app.apply(
    lambda row: row['AMT_CREDIT'] / avg_months if pd.isnull(row['AMT_ANNUITY']) and row['NAME_CONTRACT_TYPE'] == 'Cash loans' else row['AMT_ANNUITY'], 
    axis=1
)

## Cleaning AMT_GOODS_PRICE column

In [10]:
app[app['AMT_GOODS_PRICE'].isna()]

,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_CURR
586,0,Revolving loans,F,N,Y,2,45000.0,135000.0,6750.0,NaN,NaN,Commercial associate,Secondary / secondary special,Married,House / apartment,0.024610,-10072,-381,-519.0,-1834,NaN,1,1,1,1,0,0,Core staff,4.0,2,2,WEDNESDAY,14,0,0,0,0,0,0,Kindergarten,0.358509,0.378174,NaN,NaN,NaN,0.9791,NaN,NaN,0.00,0.0345,0.0417,NaN,NaN,NaN,0.0070,NaN,NaN,NaN,NaN,0.9791,NaN,NaN,0.000,0.0345,0.0417,NaN,NaN,NaN,0.0073,NaN,NaN,NaN,NaN,0.9791,NaN,NaN,0.00,0.0345,0.0417,NaN,NaN,NaN,0.0071,NaN,NaN,NaN,block of flats,0.0079,"Stone, brick",No,2.0,1.0,2.0,1.0,-2011.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,192094
4758,0,Revolving loans,F,N,N,0,157500.0,450000.0,22500.0,NaN,NaN,Working,Secondary / secondary special,Married,House / apartment,0.010006,-11993,-2921,-1289.0,-1948,NaN,1,1,1,1,1,1,Private service staff,2.0,2,2,SATURDAY,13,0,0,0,0,0,0,Business Entity Type 3,0.505609,0.464614,0.537070,0.2598,0.1406,0.9980,NaN,NaN,0.28,0.2414,0.3333,NaN,0.0189,NaN,NaN,NaN,0.0188,0.2647,0.1459,0.9980,NaN,NaN,0.282,0.2414,0.3333,NaN,0.0194,NaN,NaN,NaN,0.0199,0.2623,0.1406,0.9980,NaN,NaN,0.28,0.2414,0.3333,NaN,0.0193,NaN,NaN,NaN,0.0192,NaN,block of flats,0.1971,Panel,No,0.0,0.0,0.0,0.0,-476.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,287047
5139,0,Revolving loans,F,N,N,0,67500.0,202500.0,10125.0,NaN,NaN,Working,Higher education,Married,House / apartment,0.008474,-9727,-2712,-4132.0,-800,NaN,1,1,1,1,1,0,Accountants,2.0,2,2,WEDNESDAY,18,0,0,0,0,0,0,Trade: type 7,0.706945,0.565849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0.0,-643.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,154797
5367,0,Revolving loans,F,N,N,1,121500.0,180000.0,9000.0,NaN,NaN,Working,Secondary / secondary special,Civil marriage,House / apartment,0.011657,-11079,-899,-3765.0,-572,NaN,1,1,1,1,1,0,Managers,3.0,1,1,WEDNESDAY,11,0,0,0,0,0,0,Government,NaN,0.645519,0.863363,0.0577,0.0350,0.9767,0.6804,0.0131,0.00,0.1034,0.1667,0.2083,0.0595,0.0471,0.0484,0.0077,0.0106,0.0588,0.0363,0.9767,0.6929,0.0132,0.000,0.1034,0.1667,0.2083,0.0608,0.0514,0.0504,0.0078,0.0112,0.0583,0.0350,0.9767,0.6847,0.0132,0.00,0.1034,0.1667,0.2083,0.0605,0.0479,0.0493,0.0078,0.0108,reg oper account,block of flats,0.0452,"Stone, brick",No,1.0,0.0,1.0,0.0,-1292.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,124841
6137,0,Revolving loans,M,N,Y,0,180000.0,450000.0,22500.0,NaN,NaN,Working,Higher education,Single / not married,House / apartment,0.032561,-9986,-1847,-4762.0,-506,NaN,1,1,1,1,1,0,Security staff,1.0,1,1,SATURDAY,18,0,0,0,0,0,0,Construction,0.477288,0.552557,0.661024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,-159.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,31671
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243716,0,Revolving loans,F,N,Y,2,67500.0,202500.0,10125.0,NaN,NaN,Working,Higher education,Married,House / apartment,0.025164,-11313,-1470,-1188.0,-3523,NaN,1,1,1,1,0,0,Sales staff,4.0,2,2,WEDNESDAY,11,0,0,0,1,0,1,Business Entity Type 3,NaN,0.449139,0.574447,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,3.0,0.0,-777.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,250861
243797,0,Revolving loans,M,N,Y,1,112500.0,270000.0,13500.0,NaN,NaN,Working,Secondary / secondary special,Married,House / apartment,0.028663,-16870,-825,-1303.0,-427,NaN,1,1,1,1,1,0,Drivers,3.0,2,2,THURSDAY,10,0,0,0,1,1,1,Self-employed,NaN,0.441976,0.459690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,3.0,1.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,294943
244636,0,Revolving loans,F,N,Y,0,126000.0,270000.0,13500.0,NaN,NaN,Working,Incomplete higher,Single / not married,With parents,0.015221,-10440,-3444,-4452.0,-3096,NaN,1,1,1,1,1,0,Core staff,1.0,2,2,THURSDAY,10,0,0,0,0,0,0,Self-employed,0.164542,0.480353,0.698668,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,-163.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,186482
244871,0,Revolving loans,M,N,Y,0,135000.0,270000.0,13500.0,NaN,NaN,Commercial associate,Secondary / secondary special,Married,Municipal apartment,0.046220,-15406,-427,-8924.0,-4101,NaN,1,1,1,1,1,0,NaN,2.0,1,1,THURSDAY,16,0,1,1,0,1,1,Security,0.715165,0.675154,0.321735,0.0619,0.0599,0.9757,NaN,NaN,0.00,0.1379,0.1250,NaN,NaN,NaN,0.0494,NaN,NaN,0.0630,0.0622,0.9757,NaN,NaN,0.000,0.1379,0.1250,NaN,NaN,NaN,0.0515,NaN,NaN,0.0625,0.0599,0.9757,NaN,NaN,0.00,0.1379,0.1250,NaN,NaN,NaN,0.0503,NaN,NaN,NaN,block of flats,0.0514,Panel,No,0.0,0.0,0.0,0.0,-188.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,169415
244989,0,Revolving loans,M,N,Y,2,67500.0,202500.0,10125.0,NaN,NaN,Working,Higher education,Married,House / apartment,0.020713,-14079,-1648,-2492.0,-4905,NaN,1,1,1,1,1,0,Laborers,4.0,3,3,THURSDAY,6,0,0,0,0,0,0,Self-employed,0.411601,0.608328,NaN,0.0825,0.0628,0.9752,NaN,NaN,0.00,0.1379,0.1667,NaN,0.0144,NaN,0.0694,NaN,0.0000,0.0840,0.0651,0.9752,NaN,NaN,0.000,0.1379,0.1667,NaN,0.0147,NaN,0.0723,NaN,0.0000,0.0833,0.0628,0.9752,NaN,NaN,0.00,0.1379,0.1667,NaN,0.0147,NaN,0.0706,NaN,0.0000,NaN,block of flats,0.0602,Panel,No,0.0,0.0,0.0,0.0,-1154.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,134938

### In all rows that this column is NaN, the result shows that the contract type is “Revolving loans”. Therefore, we fillna in this column with the median value where all the customers requiring “Revolving loans”

In [ ]:
# Median of AMT_GOODS_PRICE when NAME_CONTRACT_TYPE = "Revolving loans"
revolving_median = app.loc[app['NAME_CONTRACT_TYPE'] == 'Revolving loans', 'AMT_GOODS_PRICE'].median()

# Fillna by the median value calculated above
app.loc[(app['NAME_CONTRACT_TYPE'] == 'Revolving loans') & (app['AMT_GOODS_PRICE'].isna()), 'AMT_GOODS_PRICE'] = revolving_median

## Cleaning NAME_TYPE_SUITE column

In [ ]:
# Unique family status filtered that NAME_TYPE_SUITE is NaN
app[app['NAME_TYPE_SUITE'].isna()]['NAME_FAMILY_STATUS'].value_counts()

NAME_FAMILY_STATUS
Married                 648
Single / not married    191
Civil marriage           92
Widow                    60
Separated                54
Unknown                   1
Name: count, dtype: int64

In [ ]:
# Find the mode of NAME_TYPE_SUITE for each group of NAME_FAMILY_STATUS
mode_by_family_status = app.groupby('NAME_FAMILY_STATUS')['NAME_TYPE_SUITE'].agg(lambda x: x.mode()[0] if not x.mode().empty else 'Unknown')
mode_by_family_status

NAME_FAMILY_STATUS
Civil marriage          Unaccompanied
Married                 Unaccompanied
Separated               Unaccompanied
Single / not married    Unaccompanied
Unknown                       Unknown
Widow                   Unaccompanied
Name: NAME_TYPE_SUITE, dtype: object

In [ ]:
# Fill with the mode filtered for each NAME_FAMILY_STATUS group, as they have a domain relationship
app['NAME_TYPE_SUITE'] = app.apply(
    lambda row: mode_by_family_status[row['NAME_FAMILY_STATUS']] if pd.isna(row['NAME_TYPE_SUITE']) else row['NAME_TYPE_SUITE'],
    axis=1
)

## Cleaning OWN_CAR_AGE column

In [ ]:
# NaN rows in OWN_CAR_AGE
missing_car_age = app[app['OWN_CAR_AGE'].isna()]

# Check if these rows are the customers that don't own car (FLAG_OWN_CAR == 'N') or not
missing_car_age_no_car = missing_car_age[missing_car_age['FLAG_OWN_CAR'] == 'N']

# Check the result
print(f"Số lượng dòng thiếu OWN_CAR_AGE: {missing_car_age.shape[0]}")
print(f"Số lượng dòng thiếu OWN_CAR_AGE và không sở hữu xe: {missing_car_age_no_car.shape[0]}")

missing_car_age_no_car

Số lượng dòng thiếu OWN_CAR_AGE: 162188
Số lượng dòng thiếu OWN_CAR_AGE và không sở hữu xe: 162184

,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_CURR
0,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.0790,0.0554,0.0,0.0000,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.0100,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,278621
1,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.008019,-19005,-3039,-9833.0,-2437,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,-617.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,139008
2,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.028663,-19932,-3038,-4311.0,-3458,NaN,1,1,0,1,0,0,Core staff,1.0,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.322738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1106.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,138348
3,0,Cash loans,M,N,Y,0,99000.0,490495.5,27517.5,454500.0,"Spouse, partner",State servant,Secondary / secondary special,Married,House / apartment,0.035792,-16941,-1588,-4970.0,-477,NaN,1,1,1,1,1,0,Laborers,2.0,2,2,WEDNESDAY,16,0,0,0,0,0,0,Other,NaN,0.354225,0.621226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-2536.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0,64140
5,0,Cash loans,F,N,Y,0,112500.0,1019610.0,33826.5,913500.0,Children,Pensioner,Secondary / secondary special,Married,House / apartment,0.018634,-20099,365243,-7427.0,-3514,NaN,1,0,0,1,0,0,NaN,2.0,2,2,WEDNESDAY,14,0,0,0,0,0,0,XNA,0.587334,0.205747,0.751724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,53466
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246004,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,225000.0,Unaccompanied,Working,Secondary / secondary special,Separated,With parents,0.032561,-9327,-236,-8456.0,-1982,NaN,1,1,0,1,0,0,Sales staff,1.0,1,1,THURSDAY,15,0,0,0,0,0,0,Services,0.145570,0.681632,NaN,0.2021,0.0887,0.9876,0.8300,0.0202,0.22,0.1034,0.6042,0.2708,0.0594,0.1484,0.1965,0.0753,0.1095,0.1008,0.0172,0.9782,0.7125,0.0172,0.0806,0.0345,0.4583,0.0417,0.0094,0.0882,0.0853,0.0,0.0125,0.2040,0.0887,0.9876,0.8323,0.0203,0.22,0.1034,0.6042,0.2708,0.0605,0.1509,0.2001,0.0757,0.1118,reg oper account,block of flats,0.2898,"Stone, brick",No,0.0,0.0,0.0,0.0,-273.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,90253
246005,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,225000.0,Unaccompanied,Pensioner,Secondary / secondary special,Widow,House / apartment,0.025164,-20775,365243,-4388.0,-4090,NaN,1,0,0,1,1,0,NaN,1.0,2,2,MONDAY,8,0,0,0,0,0,0,XNA,NaN,0.115992,NaN,0.0247,0.0435,0.9727,0.6260,0.0022,0.00,0.1034,0.0833,0.1250,0.0579,0.0202,0.0257,0.0000,0.0000,0.0252,0.0451,0.9727,0.6406,0.0022,0.0000,0.1034,0.0833,0.1250,0.0592,0.0220,0.0267,0.0,0.0000,0.0250,0.0435,0.9727,0.6310,0.0022,0.00,0.1034,0.0833,0.1250,0.0589,0.0205,0.0261,0.0000,0.0000,reg oper account,block of flats,0.0214,"Stone, brick",No,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,9027
246006,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,585000.0,Unaccompanied,Working,Higher education,Separated,House / apartment,0.005002,-14966,-7921,-6737.0,-5150,NaN,1,1,0,1,0,1,Managers,1.0,3,3,THURSDAY,9,0,0,0,0,1,1,School,0.744026,0.535722,0.218859,0.1031,0.0862,0.9816,0.7484,0.0123,0.00,0.2069,0.1667,0.2083,NaN,0.0841,0.9279,0.0000,0.0000,0.1050,0.0894,0.9816,0.7583,0.0124,0.0000,0.2069,0.1667,0.2083,NaN,0.0918,0.9667,0.0,0.0000,0.1041,0.0862,0.9816,0.7518,0.0124,0.00,0.2069,0.1667,0.2083,NaN,0.0855,0.9445,0.0000,0.0000,reg oper account,block of flats,0.7970,Panel,No,6.0,0.0,6.0,0.0,-1909.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0,163598
246007,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,319500.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.005313,-11961,-4786,-2562.0,-931,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,9,0,0,0,1,1,0,Business Entity Type 1,NaN,0.514163,0.661024,0.0124,NaN,0.9771,NaN,NaN,NaN,0.0690,0.0417,NaN,NaN,NaN,0.0061,NaN,NaN,0.0126,NaN,0.9772,NaN,NaN,NaN,0.0690,0.0417,NaN,NaN,NaN,0.0063,NaN,NaN,0.0125,NaN,0.9771,NaN,NaN,NaN,0.0690,0.0417,NaN,NaN,NaN,0.0062,NaN,NaN,NaN,block of flats,0.0086,"Stone, brick",No,0.0,0.0,0.0,0.0,-322.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,300375
246008,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.046220,-16856,-1262,-5128.0,-410,NaN,1,1,1,1,1,0,Laborers,2.0,1,1,THURSDAY,20,0,0,0,0,1,1,Business Entity Type 3,0.734460,0.708569,0.113922,0.0742,0.0526,0.9881,NaN,0.0176,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0791,NaN,0.0000,0.0756,0.0546,0.9881,NaN,0.0178,0.0806,0.0690,0.3750,NaN,NaN,NaN,0.0824,NaN,0.0000,0.0749,0.0526,0.9881,NaN,0.0177,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0805,NaN,0.0000,NaN,block of flats,0.0718,Panel,No,0.0,0.0,0.0,0.0,-787.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0,258328

In [16]:
app[(app['FLAG_OWN_CAR'] == 'Y') & (app['OWN_CAR_AGE'] == 0)]

,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_CURR
204,0,Cash loans,M,Y,N,0,202500.0,526491.0,26878.5,454500.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.022625,-14811,-7668,-1761.0,-4268,0.0,1,1,1,1,1,0,Managers,2.0,2,2,TUESDAY,15,0,0,0,0,0,0,Transport: type 4,0.645151,0.658704,0.697147,0.4072,0.2893,0.9816,0.7484,0.0089,0.44,0.3793,0.3333,0.3750,0.1754,0.3261,0.4133,0.027,0.0083,0.4149,0.3002,0.9816,0.7583,0.0090,0.4431,0.3793,0.3333,0.3750,0.1794,0.3563,0.4306,0.0272,0.0087,0.4112,0.2893,0.9816,0.7518,0.0090,0.44,0.3793,0.3333,0.3750,0.1784,0.3318,0.4207,0.0272,0.0084,NaN,block of flats,0.3288,Panel,No,0.0,0.0,0.0,0.0,-669.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0,48635
328,0,Cash loans,F,Y,Y,0,225000.0,1345500.0,39469.5,1345500.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.026392,-15601,-3880,-9642.0,-2242,0.0,1,1,0,1,0,0,NaN,2.0,2,2,SATURDAY,14,0,0,0,0,0,0,Business Entity Type 2,NaN,0.619853,0.657784,0.1412,NaN,0.9841,NaN,NaN,0.16,0.1379,0.3750,NaN,0.1125,NaN,0.1449,NaN,0.0651,0.1439,NaN,0.9841,NaN,NaN,0.1611,0.1379,0.3750,NaN,0.1150,NaN,0.1509,NaN,0.0690,0.1426,NaN,0.9841,NaN,NaN,0.16,0.1379,0.3750,NaN,0.1144,NaN,0.1475,NaN,0.0665,NaN,block of flats,0.1281,"Stone, brick",No,3.0,0.0,2.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,1.0,0.0,18627
423,0,Cash loans,F,Y,Y,1,229500.0,1006920.0,72778.5,900000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.008230,-9920,-279,-4568.0,-1344,0.0,1,1,0,1,0,0,Laborers,3.0,2,2,FRIDAY,15,0,1,1,0,0,0,Industry: type 12,NaN,0.655496,NaN,0.0825,0.0664,0.9767,0.6804,0.0289,0.00,0.1379,0.1667,0.2083,0.0180,0.0672,0.0703,0.000,0.0000,0.0840,0.0689,0.9767,0.6929,0.0292,0.0000,0.1379,0.1667,0.2083,0.0184,0.0735,0.0733,0.0000,0.0000,0.0833,0.0664,0.9767,0.6847,0.0291,0.00,0.1379,0.1667,0.2083,0.0183,0.0684,0.0716,0.0000,0.0000,reg oper account,block of flats,0.0711,Panel,No,1.0,0.0,1.0,0.0,-1402.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0,288481
453,0,Cash loans,F,Y,Y,2,76500.0,119925.0,13045.5,112500.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.014464,-12463,-1631,-2688.0,-3524,0.0,1,1,0,1,1,0,NaN,4.0,2,2,THURSDAY,3,0,0,0,0,0,0,Business Entity Type 3,NaN,0.373813,0.643026,0.0082,0.0155,0.9692,NaN,NaN,0.00,0.0345,0.0417,NaN,0.0156,NaN,0.0078,NaN,0.0000,0.0084,0.0161,0.9692,NaN,NaN,0.0000,0.0345,0.0417,NaN,0.0160,NaN,0.0081,NaN,0.0000,0.0083,0.0155,0.9692,NaN,NaN,0.00,0.0345,0.0417,NaN,0.0159,NaN,0.0079,NaN,0.0000,NaN,block of flats,0.0061,"Stone, brick",No,1.0,0.0,1.0,0.0,-355.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0,269528
646,0,Cash loans,M,Y,Y,0,337500.0,900000.0,26446.5,900000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.022800,-21910,-4800,-216.0,-5070,0.0,1,1,0,1,0,0,Core staff,2.0,2,2,THURSDAY,10,0,0,0,0,0,0,Industry: type 9,NaN,0.720063,NaN,0.0825,0.1818,0.9945,NaN,NaN,0.12,0.1034,0.3333,NaN,0.0621,NaN,0.1014,NaN,0.0766,0.0840,0.1887,0.9945,NaN,NaN,0.1208,0.1034,0.3333,NaN,0.0635,NaN,0.1056,NaN,0.0811,0.0833,0.1818,0.9945,NaN,NaN,0.12,0.1034,0.3333,NaN,0.0632,NaN,0.1032,NaN,0.0782,NaN,block of flats,0.1149,"Stone, brick",No,0.0,0.0,0.0,0.0,-2384.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,219983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245564,0,Cash loans,M,Y,N,0,315000.0,364896.0,23724.0,315000.0,Unaccompanied,Working,Higher education,Single / not married,House / apartment,0.019101,-9642,-926,-1050.0,-2317,0.0,1,1,0,1,0,0,Core staff,1.0,2,2,TUESDAY,11,0,0,0,0,0,0,Legal Services,NaN,0.656369,0.474051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-506.0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,123816
245720,0,Cash loans,M,Y,Y,0,225000.0,1174090.5,46692.0,1080000.0,Unaccompanied,Pensioner,Secondary / secondary special,Married,House / apartment,0.019101,-22704,365243,-11452.0,-4584,0.0,1,0,0,1,0,0,NaN,2.0,2,2,TUESDAY,14,0,0,0,0,0,0,XNA,NaN,0.754799,0.647977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,5.0,0.0,-706.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0,38718
245752,0,Cash loans,F,Y,Y,0,315000.0,1066500.0,31180.5,1066500.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.019689,-12932,-5644,-945.0,-1479,0.0,1,1,0,1,0,1,Core staff,2.0,2,2,THURSDAY,14,0,0,0,0,0,0,Government,0.789243,0.663129,0.391055,0.1031,0.0582,0.9866,0.8164,0.0178,0.10,0.0862,0.3750,0.2083,0.0245,0.0841,0.1153,0.000,0.0000,0.0840,0.0483,0.9866,0.8236,0.0075,0.0806,0.0690,0.3750,0.0000,0.0250,0.0735,0.0959,0.0000,0.0000,0.1041,0.0582,0.9866,0.8189,0.0179,0.10,0.0862,0.3750,0.2083,0.0249,0.0855,0.1173,0.0000,0.0000,reg oper spec account,block of flats,0.0724,Panel,No,1.0,0.0,1.0,0.0,-1669.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,22786
245831,0,Cash loans,M,Y,Y,0,225000.0,1035000.0,30393.0,1035000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.026392,-14547,-5097,-515.0,-4804,0.0,1,1,0,1,0,0,Drivers,2.0,2,2,TUESDAY,14,0,0,0,0,0,0,Industry: type 9,NaN,0.717087,0.295583,0.1835,NaN,0.9841,NaN,NaN,0.20,0.1724,0.3333,NaN,0.1416,NaN,0.1900,NaN,0.0000,0.1870,NaN,0.9841,NaN,NaN,0.2014,0.1724,0.3333,NaN,0.1448,NaN,0.1979,NaN,0.0000,0.1853,NaN,0.9841,NaN,NaN,0.20,0.1724,0.3333,NaN,0.1440,NaN,0.1934,NaN,0.0000,NaN,block of flats,0.1494,Panel,No,2.0,1.0,2.0,1.0,-1715.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,3.0,28210
245997,0,Cash loans,F,Y,Y,0,180000.0,270126.0,12028.5,193500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.007020,-16679,-1222,-1916.0,-222,0.0,1,1,0,1,0,0,Sales staff,2.0,2,2,THURSDAY,13,0,0,0,0,1,1,Trade: type 7,0.251096,0.651306,0.524496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1344.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0,164884

### There are 162,188 NaN rows, of which 162,184 customers don’t own a car. So for those who own a car, we fillna with median, and for those who do not, we fillna with -1

In [ ]:
# Fill -1 for those who don't own car
app.loc[app['FLAG_OWN_CAR'] == 'N', 'OWN_CAR_AGE'] = -1

# Fill median for those who own car
median_car_age = app.loc[app['FLAG_OWN_CAR'] == 'Y', 'OWN_CAR_AGE'].median()
app.loc[(app['FLAG_OWN_CAR'] == 'Y') & (app['OWN_CAR_AGE'].isna()), 'OWN_CAR_AGE'] = median_car_age

## Cleaning OCCUPATION_TYPE column

In [ ]:
# Divide AMT_INCOME_TOTAL into groups (quantile)
app['INCOME_QUANTILE'] = pd.qcut(app['AMT_INCOME_TOTAL'], q=4, labels=['Low', 'Medium', 'High', 'Very High'])

In [ ]:
# Find the most popular value in each group
occupation_mode = app.groupby(['NAME_EDUCATION_TYPE', 'INCOME_QUANTILE'])['OCCUPATION_TYPE'].agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
print(occupation_mode)

NAME_EDUCATION_TYPE            INCOME_QUANTILE
Academic degree                Low                   Managers
                               Medium                Managers
                               High                Core staff
                               Very High             Managers
Higher education               Low                 Core staff
                               Medium              Core staff
                               High                Core staff
                               Very High             Managers
Incomplete higher              Low                Sales staff
                               Medium                Laborers
                               High                  Laborers
                               Very High             Managers
Lower secondary                Low                   Laborers
                               Medium                Laborers
                               High                  Laborers
                               Very High             Laborers
Secondary / secondary special  Low                   Laborers
                               Medium                Laborers
                               High                  Laborers
                               Very High             Laborers
Name: OCCUPATION_TYPE, dtype: object

C:\Users\Admin\AppData\Local\Temp\ipykernel_20936\1438009852.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  occupation_mode = app.groupby(['NAME_EDUCATION_TYPE', 'INCOME_QUANTILE'])['OCCUPATION_TYPE'].agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)

### Fill with the mode within groups based on NAME_EDUCATION_TYPE and INCOME_QUANTILE (low/medium/high/very high), as they have a domain relationship

In [20]:
def fill_occupation(row):
    if pd.isna(row['OCCUPATION_TYPE']):
        return occupation_mode.get((row['NAME_EDUCATION_TYPE'], row['INCOME_QUANTILE']), row['OCCUPATION_TYPE'])
    else:
        return row['OCCUPATION_TYPE']

app['OCCUPATION_TYPE'] = app.apply(fill_occupation, axis=1)

## Cleaning CNT_FAM_MEMBERS column

In [21]:
app[app['CNT_FAM_MEMBERS'].isna()]

,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_CURR,INCOME_QUANTILE
33550,0,Revolving loans,M,N,Y,0,450000.0,675000.0,33750.0,270000.0,Unknown,Commercial associate,Lower secondary,Unknown,Municipal apartment,0.015221,-12396,-1161,-3265.0,-4489,-1.0,1,1,1,1,1,0,Managers,NaN,2,2,THURSDAY,15,0,1,1,0,1,1,Insurance,0.628564,0.700618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.0,3.0,0.0,-876.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,224006,Very High

### Only 1 NaN value in a customer whose family status is unknown, therefore fillna with 0

In [22]:
app['CNT_FAM_MEMBERS'].fillna(value= 0, inplace= True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_20936\126323430.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app['CNT_FAM_MEMBERS'].fillna(value= 0, inplace= True)

## Cleaning EXT_SOURCE columns

In [23]:
app[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']].describe()

        EXT_SOURCE_1  EXT_SOURCE_2   EXT_SOURCE_3
count  107484.000000  2.454800e+05  197185.000000
mean        0.502462  5.143854e-01       0.511034
std         0.210813  1.910533e-01       0.194837
min         0.014568  8.173617e-08       0.000527
25%         0.334376  3.922228e-01       0.370650
50%         0.506427  5.658916e-01       0.537070
75%         0.675074  6.637452e-01       0.669057
max         0.951624  8.549997e-01       0.896010

In [ ]:
# Fillna with the median as this comes from external information
for col in ['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']:
    app[col].fillna(app[col].median(), inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_20936\2578508374.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app[col].fillna(app[col].median(), inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_20936\2578508374.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app[col].fillna(app[col].median(), inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_20936\2578508374.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app[col].fillna(app[col].median(), inplace=True)

## Cleaning the remaining columns

In [ ]:
# Find the other missing columns
missing_cols = app.columns[app.isna().any()].tolist()

# For other columns, fillna with the median where columns are numerical, otherwise fillna with the mode
for col in missing_cols:
    if app[col].dtype == 'object': 
        app[col] = app[col].fillna(app[col].mode()[0])
    else:  
        app[col] = app[col].fillna(app[col].median())

In [ ]:
# Export cleaned dataset
file_path = r'C:\Users\Admin\Desktop\Final data prep\cleaned_data\application_test.csv'
app.to_csv(file_path, index=False)

print(f"CSV file has been saved to {file_path}")

CSV file has been saved to C:\Users\Admin\Desktop\Final data prep\cleaned_data\application_train.csv