In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np

In [ ]:
# Load the dataset
credit = pd.read_csv(r"C:\Users\Admin\Downloads\final_dataprep\dseb63_final_project_DP_dataset\dseb63_credit_card_balance.csv")
credit

,SK_ID_PREV,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
0,2582071,-1,63975.555,45000,2250.0,2250.0,0.0,0.0,2250.0,2250.0,2250.0,60175.080,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0,87788
1,2582071,-82,16809.210,67500,0.0,0.0,0.0,0.0,3375.0,9000.0,9000.0,15488.685,16809.210,16809.210,0.0,0,0.0,0.0,18.0,Active,0,0,87788
2,2582071,-84,27577.890,67500,0.0,0.0,0.0,0.0,3375.0,4500.0,4500.0,26125.020,27577.890,27577.890,0.0,0,0.0,0.0,16.0,Active,0,0,87788
3,2582071,-7,65159.235,45000,0.0,0.0,0.0,0.0,2250.0,2250.0,2250.0,60301.170,65609.235,65609.235,0.0,0,0.0,0.0,63.0,Active,0,0,87788
4,2582071,-59,70475.850,67500,24750.0,24750.0,0.0,0.0,3375.0,4500.0,4500.0,63975.015,70475.850,70475.850,4.0,4,0.0,0.0,41.0,Active,0,0,87788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3227960,1551072,-1,0.000,202500,NaN,0.0,NaN,NaN,0.0,NaN,0.0,0.000,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0,259579
3227961,2339982,-1,0.000,45000,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.000,0.000,0.000,0.0,0,0.0,0.0,0.0,Active,0,0,220697
3227962,2720102,-1,0.000,225000,NaN,0.0,NaN,NaN,0.0,NaN,0.0,0.000,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0,93573
3227963,1897864,-2,0.000,270000,NaN,0.0,NaN,NaN,0.0,NaN,0.0,0.000,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0,11072
3227964,2481982,-1,0.000,270000,NaN,0.0,NaN,NaN,0.0,NaN,0.0,0.000,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0,258032

In [ ]:
credit.rename(columns={'AMT_RECIVABLE': 'AMT_RECEIVABLE'}, inplace=True)

In [ ]:
# Check overall info of the dataset
credit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3227965 entries, 0 to 3227964
Data columns (total 23 columns):
 #   Column                      Dtype
---  ------                      -----
 0   SK_ID_PREV                  int64
 1   MONTHS_BALANCE              int64
 2   AMT_BALANCE                 float64
 3   AMT_CREDIT_LIMIT_ACTUAL     int64
 4   AMT_DRAWINGS_ATM_CURRENT    float64
 5   AMT_DRAWINGS_CURRENT        float64
 6   AMT_DRAWINGS_OTHER_CURRENT  float64
 7   AMT_DRAWINGS_POS_CURRENT    float64
 8   AMT_INST_MIN_REGULARITY     float64
 9   AMT_PAYMENT_CURRENT         float64
 10  AMT_PAYMENT_TOTAL_CURRENT   float64
 11  AMT_RECEIVABLE_PRINCIPAL    float64
 12  AMT_RECEIVABLE              float64
 13  AMT_TOTAL_RECEIVABLE        float64
 14  CNT_DRAWINGS_ATM_CURRENT    float64
 15  CNT_DRAWINGS_CURRENT        int64
 16  CNT_DRAWINGS_OTHER_CURRENT  float64
 17  CNT_DRAWINGS_POS_CURRENT    float64
 18  CNT_INSTALMENT_MATURE_CUM   float64
 19  NAME_CONTRACT_STATUS        object
 20  SK_DPD                      int64
 21  SK_DPD_DEF                  int64
 22  SK_ID_CURR                  int64
dtypes: float64(15), int64(7), object(1)
memory usage: 566.4+ MB

In [ ]:
# Check for null values
credit.isnull().sum()

SK_ID_PREV                         0
MONTHS_BALANCE                     0
AMT_BALANCE                        0
AMT_CREDIT_LIMIT_ACTUAL            0
AMT_DRAWINGS_ATM_CURRENT      605754
AMT_DRAWINGS_CURRENT               0
AMT_DRAWINGS_OTHER_CURRENT    605754
AMT_DRAWINGS_POS_CURRENT      605754
AMT_INST_MIN_REGULARITY       264384
AMT_PAYMENT_CURRENT           620093
AMT_PAYMENT_TOTAL_CURRENT          0
AMT_RECEIVABLE_PRINCIPAL           0
AMT_RECEIVABLE                     0
AMT_TOTAL_RECEIVABLE               0
CNT_DRAWINGS_ATM_CURRENT      605754
CNT_DRAWINGS_CURRENT               0
CNT_DRAWINGS_OTHER_CURRENT    605754
CNT_DRAWINGS_POS_CURRENT      605754
CNT_INSTALMENT_MATURE_CUM     264384
NAME_CONTRACT_STATUS               0
SK_DPD                             0
SK_DPD_DEF                         0
SK_ID_CURR                         0
dtype: int64

In [ ]:
# Fillna with 0 for more convenient calculations
credit.fillna(0, inplace=True)

## Cleaning Drawing Columns

In [ ]:
# There are some drawing values below 0, which is inappropriate
credit[credit['AMT_DRAWINGS_CURRENT'] < 0]

,SK_ID_PREV,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECEIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
739495,2340075,-73,1718.1,180000,0.0,-519.57,0.0,0.0,9000.00,182340.000,182340.0,0.0,0.0,0.0,0.0,0,0.0,0.0,18.0,Active,0,0,97301
929338,2592574,-96,0.0,270000,0.0,-6211.62,0.0,0.0,192.33,14672.205,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,7.0,Active,0,0,33858

In [ ]:
# Change to positve values
credit.loc[credit['AMT_DRAWINGS_CURRENT'] < 0,'AMT_DRAWINGS_CURRENT'] = abs(credit['AMT_DRAWINGS_CURRENT'])

In [ ]:
# There are some drawing values below 0, which is inappropriate
credit.loc[credit['AMT_DRAWINGS_ATM_CURRENT'] < 0]

,SK_ID_PREV,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECEIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
1990734,1793522,-20,0.0,0,-6827.31,0.0,0.0,0.0,2102.31,2172.69,2172.69,0.0,0.0,0.0,1.0,1,0.0,0.0,60.0,Active,0,0,71513

In [ ]:
# Change to positve values
credit.loc[credit['AMT_DRAWINGS_ATM_CURRENT'] < 0,'AMT_DRAWINGS_ATM_CURRENT'] = abs(credit['AMT_DRAWINGS_ATM_CURRENT'])

In [ ]:
'''
The column AMT_DRAWINGS_CURRENT is the sum of the drawing amount by all methods, 
but there exist some cases where the sum is not equal to AMT_DRAWINGS_CURRENT
'''
credit[(abs(credit['AMT_DRAWINGS_CURRENT'] - 
            (credit['AMT_DRAWINGS_ATM_CURRENT'] + 
             credit['AMT_DRAWINGS_POS_CURRENT'] + 
             credit['AMT_DRAWINGS_OTHER_CURRENT'])) > 1e-6)]

,SK_ID_PREV,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECEIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
311,1441883,-4,0.0,270000,0.0,1448.640,0.0,0.0,1159.155,0.000,0.000,0.0,0.0,0.0,0.0,0,0.0,0.0,3.0,Completed,0,0,85482
434,2016842,-8,0.0,0,0.0,1277.145,0.0,0.0,0.000,1277.145,1277.145,0.0,0.0,0.0,0.0,0,0.0,0.0,2.0,Active,0,0,280613
439,1189095,-1,0.0,450000,0.0,156.960,0.0,0.0,2250.000,7757.190,7757.190,0.0,0.0,0.0,0.0,0,0.0,0.0,25.0,Completed,0,0,18319
1236,1894367,-1,0.0,0,0.0,2145.780,0.0,0.0,811.035,2664.450,2664.450,0.0,0.0,0.0,0.0,0,0.0,0.0,8.0,Completed,0,0,28440
1658,2439019,-4,0.0,135000,0.0,2048.220,0.0,0.0,0.000,2048.220,2048.220,0.0,0.0,0.0,0.0,0,0.0,0.0,6.0,Completed,0,0,145734
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3226010,1652773,-4,0.0,225000,0.0,3.105,0.0,0.0,225.000,225.000,225.000,0.0,0.0,0.0,0.0,0,0.0,0.0,3.0,Completed,0,0,125178
3227452,1268705,-3,0.0,202500,0.0,166.455,0.0,0.0,2250.000,0.000,0.000,0.0,0.0,0.0,0.0,0,0.0,0.0,1.0,Active,0,0,123114
3227573,2386587,-2,0.0,45000,0.0,6750.000,0.0,0.0,0.000,6750.000,6750.000,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,Active,0,0,185463
3227861,2421393,-2,0.0,0,0.0,90000.000,0.0,0.0,0.000,90000.000,90000.000,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,Active,0,0,174892
3227954,1362365,-1,135000.0,0,0.0,135000.000,0.0,0.0,0.000,0.000,0.000,135000.0,135000.0,135000.0,0.0,0,0.0,0.0,0.0,Active,0,0,211185

In [12]:
credit[(credit['AMT_DRAWINGS_CURRENT'] > 0) & (credit['AMT_DRAWINGS_ATM_CURRENT'] == 0) & (credit['AMT_DRAWINGS_POS_CURRENT'] == 0) & (credit['AMT_DRAWINGS_OTHER_CURRENT'] == 0)]

,SK_ID_PREV,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECEIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
311,1441883,-4,0.0,270000,0.0,1448.640,0.0,0.0,1159.155,0.000,0.000,0.0,0.0,0.0,0.0,0,0.0,0.0,3.0,Completed,0,0,85482
434,2016842,-8,0.0,0,0.0,1277.145,0.0,0.0,0.000,1277.145,1277.145,0.0,0.0,0.0,0.0,0,0.0,0.0,2.0,Active,0,0,280613
439,1189095,-1,0.0,450000,0.0,156.960,0.0,0.0,2250.000,7757.190,7757.190,0.0,0.0,0.0,0.0,0,0.0,0.0,25.0,Completed,0,0,18319
1236,1894367,-1,0.0,0,0.0,2145.780,0.0,0.0,811.035,2664.450,2664.450,0.0,0.0,0.0,0.0,0,0.0,0.0,8.0,Completed,0,0,28440
1658,2439019,-4,0.0,135000,0.0,2048.220,0.0,0.0,0.000,2048.220,2048.220,0.0,0.0,0.0,0.0,0,0.0,0.0,6.0,Completed,0,0,145734
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3226010,1652773,-4,0.0,225000,0.0,3.105,0.0,0.0,225.000,225.000,225.000,0.0,0.0,0.0,0.0,0,0.0,0.0,3.0,Completed,0,0,125178
3227452,1268705,-3,0.0,202500,0.0,166.455,0.0,0.0,2250.000,0.000,0.000,0.0,0.0,0.0,0.0,0,0.0,0.0,1.0,Active,0,0,123114
3227573,2386587,-2,0.0,45000,0.0,6750.000,0.0,0.0,0.000,6750.000,6750.000,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,Active,0,0,185463
3227861,2421393,-2,0.0,0,0.0,90000.000,0.0,0.0,0.000,90000.000,90000.000,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,Active,0,0,174892
3227954,1362365,-1,135000.0,0,0.0,135000.000,0.0,0.0,0.000,0.000,0.000,135000.0,135000.0,135000.0,0.0,0,0.0,0.0,0.0,Active,0,0,211185

In [ ]:
# If all other methods are 0: distribute the total equally across the columns
condition1 = (credit['AMT_DRAWINGS_CURRENT'] > 0) & \
             (credit['AMT_DRAWINGS_ATM_CURRENT'] == 0) & \
             (credit['AMT_DRAWINGS_POS_CURRENT'] == 0) & \
             (credit['AMT_DRAWINGS_OTHER_CURRENT'] == 0)

credit.loc[condition1, ['AMT_DRAWINGS_ATM_CURRENT', 'AMT_DRAWINGS_POS_CURRENT', 'AMT_DRAWINGS_OTHER_CURRENT']] = \
    np.tile((credit.loc[condition1, 'AMT_DRAWINGS_CURRENT'] / 3).to_numpy(), (3, 1)).T

In [14]:
credit[(credit['AMT_DRAWINGS_CURRENT'] > 0) & (credit['AMT_DRAWINGS_ATM_CURRENT'] > 0) & (credit['AMT_DRAWINGS_POS_CURRENT'] == 0) & (credit['AMT_DRAWINGS_OTHER_CURRENT'] == 0) &(abs(credit['AMT_DRAWINGS_CURRENT'] - 
            (credit['AMT_DRAWINGS_ATM_CURRENT'] + 
             credit['AMT_DRAWINGS_POS_CURRENT'] + 
             credit['AMT_DRAWINGS_OTHER_CURRENT'])) > 1e-6)]

,SK_ID_PREV,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECEIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
139513,1118507,-14,0.000,292500,135000.0,141750.000,0.0,0.0,2250.000,159285.150,157035.150,0.000,0.000,0.000,3.0,3,0.0,0.0,1.0,Active,0,0,240039
373376,1872797,-79,1421.505,180000,22500.0,49500.000,0.0,0.0,9000.000,221535.000,221535.000,0.000,0.000,0.000,1.0,1,0.0,0.0,5.0,Active,0,0,170326
538562,2076408,-89,18991.755,157500,18000.0,33750.000,0.0,0.0,1575.000,19611.990,0.000,15713.010,18991.755,18991.755,1.0,1,0.0,0.0,8.0,Active,0,0,88718
798090,2804227,-43,140103.450,135000,4500.0,13500.000,0.0,0.0,6750.000,7200.000,7200.000,133654.905,140103.450,140103.450,2.0,2,0.0,0.0,56.0,Active,0,0,21816
866989,2386683,-33,48532.365,45000,45000.0,45241.065,0.0,0.0,0.000,0.000,0.000,45000.000,48773.430,48773.430,1.0,1,0.0,0.0,21.0,Active,0,0,265682
946750,1912727,-35,313267.005,247500,292500.0,292863.330,0.0,0.0,0.000,0.000,0.000,292500.000,313630.335,313630.335,4.0,4,0.0,0.0,60.0,Active,0,0,117843
1127540,1668391,-7,0.000,292500,4500.0,4637.655,0.0,0.0,15168.645,311821.695,309571.695,0.000,0.000,0.000,1.0,1,0.0,0.0,4.0,Active,0,0,69752
1219417,1450228,-3,0.000,270000,13500.0,16376.490,0.0,0.0,2250.000,291410.550,291410.550,0.000,0.000,0.000,1.0,1,0.0,0.0,3.0,Completed,0,0,206215
1498156,1768381,-81,36318.780,135000,36000.0,38939.490,0.0,0.0,6419.610,11250.000,11250.000,34109.100,36318.780,36318.780,1.0,1,0.0,0.0,15.0,Active,0,0,240608
1701724,1944851,-41,145970.550,157500,135000.0,157500.000,0.0,0.0,462.600,22500.000,22500.000,133675.965,145970.550,145970.550,1.0,1,0.0,0.0,38.0,Active,0,0,293357
1817706,1200960,-30,7094.565,45000,2250.0,5850.000,0.0,0.0,2519.100,58968.090,58725.000,3600.000,5749.065,5749.065,1.0,1,0.0,0.0,1.0,Active,0,0,241477
1908756,1839391,-76,64161.270,67500,9000.0,40500.000,0.0,0.0,3375.000,36000.000,36000.000,61356.780,63487.755,63487.755,1.0,1,0.0,0.0,20.0,Active,0,0,19386
1908848,2592876,-69,64161.270,67500,9000.0,40500.000,0.0,0.0,3375.000,36000.000,36000.000,61356.780,63487.755,63487.755,1.0,1,0.0,0.0,20.0,Active,0,0,7187
2384148,1464249,-12,4106.520,765000,85500.0,90058.635,0.0,0.0,3434.265,161345.295,159095.295,0.000,70.020,70.020,3.0,3,0.0,0.0,1.0,Active,0,0,58546
2521218,2658353,-14,454028.715,450000,45000.0,67500.000,0.0,0.0,24480.045,24750.000,24750.000,441959.085,454028.715,454028.715,1.0,1,0.0,0.0,19.0,Active,0,0,190875
2685096,1118323,-7,0.000,0,45000.0,1350000.000,0.0,0.0,0.000,1350000.000,1350000.000,0.000,0.000,0.000,1.0,1,0.0,0.0,0.0,Active,0,0,126370
2689052,2705613,-20,0.000,450000,4500.0,5103.090,0.0,0.0,11945.790,266343.975,264093.975,0.000,0.000,0.000,1.0,1,0.0,0.0,6.0,Active,0,0,284514
2804332,1092206,-55,140117.400,135000,49950.0,54450.000,0.0,0.0,6750.000,45000.000,45000.000,125793.630,139321.710,139321.710,9.0,9,0.0,0.0,20.0,Active,0,0,177378
2882581,1970051,-29,205705.935,450000,202500.0,214155.000,0.0,0.0,0.000,0.000,0.000,202500.000,203014.935,203014.935,2.0,2,0.0,0.0,0.0,Active,0,0,68071
2889930,1766436,-9,0.000,0,4500.0,135000.000,0.0,0.0,0.000,135000.000,135000.000,0.000,0.000,0.000,1.0,1,0.0,0.0,0.0,Active,0,0,69802
2898236,2173694,-7,0.000,0,45000.0,90004.500,0.0,0.0,0.000,46575.000,45004.500,0.000,0.000,0.000,2.0,2,0.0,0.0,0.0,Active,0,0,73883
2957071,1376783,-15,1062.000,0,90000.0,225000.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,4.0,4,0.0,0.0,0.0,Active,0,0,155114
2980172,1825284,-3,0.000,765000,27000.0,32125.950,0.0,0.0,33140.880,813191.715,810941.715,0.000,0.000,0.000,2.0,2,0.0,0.0,11.0,Completed,0,0,217935
3002677,1864769,-25,7094.565,45000,2250.0,5850.000,0.0,0.0,2519.100,58968.090,58725.000,3600.000,5749.065,5749.065,1.0,1,0.0,0.0,1.0,Active,0,0,278509
3027609,1499557,-11,0.000,0,45000.0,1125000.000,0.0,0.0,0.000,1125000.000,1125000.000,0.000,0.000,0.000,1.0,1,0.0,0.0,0.0,Active,0,0,225818
3045188,2487193,-13,0.000,292500,18000.0,18131.940,0.0,0.0,14081.940,320776.380,318526.380,0.000,130.500,130.500,2.0,2,0.0,0.0,3.0,Active,0,0,77003
3070581,1160267,-10,19345.500,720000,18000.0,24750.000,0.0,0.0,0.000,0.000,0.000,18000.000,18000.000,18000.000,1.0,1,0.0,0.0,0.0,Active,0,0,218689
3082662,2178349,-14,6716.250,765000,74250.0,104639.175,0.0,0.0,35467.200,803700.000,765034.470,0.000,6716.250,6716.250,3.0,3,0.0,0.0,6.0,Active,0,0,72513
3119307,1517447,-6,0.000,180000,3600.0,6306.165,0.0,0.0,9243.765,207525.105,205275.105,0.000,0.000,0.000,1.0,1,0.0,0.0,4.0,Active,0,0,287160
3155552,2668154,-11,141186.015,135000,135000.0,162450.000,0.0,0.0,0.000,27450.000,27450.000,135000.000,136474.515,136474.515,3.0,3,0.0,0.0,0.0,Active,0,0,58587
3165009,2259020,-13,0.000,450000,40500.0,40814.325,0.0,0.0,8921.610,312967.845,310717.845,0.000,0.000,0.000,4.0,4,0.0,0.0,3.0,Active,0,0,264150
3210130,2445760,-4,0.000,135000,45000.0,45004.500,0.0,0.0,0.000,48600.000,46804.500,0.000,0.000,0.000,1.0,1,0.0,0.0,0.0,Active,0,0,66589
3210714,1305048,-7,1781.280,90000,6300.0,8085.015,0.0,0.0,4356.765,95220.000,95220.000,0.000,210.780,210.780,1.0,1,0.0,0.0,2.0,Active,0,0,207029
3214304,1982484,-7,0.000,0,22500.0,90000.000,0.0,0.0,0.000,90000.000,90000.000,0.000,0.000,0.000,1.0,1,0.0,0.0,0.0,Active,0,0,229021

In [15]:
credit[(credit['AMT_DRAWINGS_CURRENT'] > 0) & (credit['AMT_DRAWINGS_ATM_CURRENT'] == 0) & (credit['AMT_DRAWINGS_POS_CURRENT'] > 0) & (credit['AMT_DRAWINGS_OTHER_CURRENT'] == 0) &(abs(credit['AMT_DRAWINGS_CURRENT'] - 
            (credit['AMT_DRAWINGS_ATM_CURRENT'] + 
             credit['AMT_DRAWINGS_POS_CURRENT'] + 
             credit['AMT_DRAWINGS_OTHER_CURRENT'])) > 1e-6)]

,SK_ID_PREV,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECEIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
92443,2517598,-18,140522.400,135000,0.0,59985.405,0.0,12735.405,3909.24,3915.000,3915.000,134255.115,140522.400,140522.400,0.0,4,0.0,4.0,2.0,Active,0,0,91007
132963,1937817,-18,26830.395,225000,0.0,83667.150,0.0,81417.150,2250.00,31500.000,29250.000,26830.395,26830.395,26830.395,0.0,12,0.0,12.0,5.0,Active,0,0,182239
206268,1594307,-7,0.000,315000,0.0,6330.015,0.0,5201.550,2250.00,311403.330,311403.330,0.000,0.000,0.000,0.0,2,0.0,2.0,13.0,Active,0,0,172855
318867,2204781,-43,140796.135,135000,0.0,8587.800,0.0,1837.800,6750.00,6750.000,6750.000,135474.660,140796.135,140796.135,0.0,2,0.0,2.0,38.0,Active,0,0,156269
355563,1721499,-1,0.000,450000,0.0,25580.655,0.0,945.000,2250.00,27351.720,27351.720,0.000,0.000,0.000,0.0,1,0.0,1.0,14.0,Completed,0,0,13414
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208941,2179488,-3,0.000,135000,0.0,3933.945,0.0,3521.250,0.00,59362.695,59362.695,0.000,0.000,0.000,0.0,2,0.0,2.0,2.0,Active,0,0,63299
3214186,1739401,-8,0.000,225000,0.0,3350.205,0.0,1632.150,225.00,2186.010,2186.010,0.000,0.000,0.000,0.0,2,0.0,2.0,3.0,Active,0,0,163709
3217229,1163850,-2,0.000,270000,0.0,4457.745,0.0,1175.400,8105.85,169856.955,169856.955,0.000,0.000,0.000,0.0,1,0.0,1.0,5.0,Active,0,0,263174
3219764,1005505,-2,86482.665,202500,0.0,93234.735,0.0,80184.735,2250.00,15776.955,15776.955,85938.615,86482.665,86482.665,0.0,25,0.0,25.0,6.0,Active,0,0,63884
3224819,2007361,-2,0.000,135000,0.0,35180.820,0.0,34482.195,2250.00,73.215,28.980,0.000,0.000,0.000,0.0,4,0.0,4.0,1.0,Active,0,0,195858

In [ ]:
# Check the result
credit[(credit['AMT_DRAWINGS_CURRENT'] > 0) & (credit['AMT_DRAWINGS_ATM_CURRENT'] == 0) & (credit['AMT_DRAWINGS_POS_CURRENT'] == 0) & (credit['AMT_DRAWINGS_OTHER_CURRENT'] > 0) &(abs(credit['AMT_DRAWINGS_CURRENT'] - 
            (credit['AMT_DRAWINGS_ATM_CURRENT'] + 
             credit['AMT_DRAWINGS_POS_CURRENT'] + 
             credit['AMT_DRAWINGS_OTHER_CURRENT'])) > 1e-6)]

Empty DataFrame
Columns: [SK_ID_PREV, MONTHS_BALANCE, AMT_BALANCE, AMT_CREDIT_LIMIT_ACTUAL, AMT_DRAWINGS_ATM_CURRENT, AMT_DRAWINGS_CURRENT, AMT_DRAWINGS_OTHER_CURRENT, AMT_DRAWINGS_POS_CURRENT, AMT_INST_MIN_REGULARITY, AMT_PAYMENT_CURRENT, AMT_PAYMENT_TOTAL_CURRENT, AMT_RECEIVABLE_PRINCIPAL, AMT_RECEIVABLE, AMT_TOTAL_RECEIVABLE, CNT_DRAWINGS_ATM_CURRENT, CNT_DRAWINGS_CURRENT, CNT_DRAWINGS_OTHER_CURRENT, CNT_DRAWINGS_POS_CURRENT, CNT_INSTALMENT_MATURE_CUM, NAME_CONTRACT_STATUS, SK_DPD, SK_DPD_DEF, SK_ID_CURR]
Index: []

In [ ]:
# If some methods have positive amounts but the sum is not equal: adjust the residual values proportionally

for col in ['AMT_DRAWINGS_ATM_CURRENT', 'AMT_DRAWINGS_POS_CURRENT', 'AMT_DRAWINGS_OTHER_CURRENT']:
    # Condition for each case
    condition2 = (credit['AMT_DRAWINGS_CURRENT'] > 0) & \
                 (credit[col] > 0) & \
                 (credit[[c for c in ['AMT_DRAWINGS_ATM_CURRENT', 'AMT_DRAWINGS_POS_CURRENT', 'AMT_DRAWINGS_OTHER_CURRENT'] if c != col]] == 0).all(axis=1) & \
                 (abs(credit['AMT_DRAWINGS_CURRENT'] - 
                      (credit['AMT_DRAWINGS_ATM_CURRENT'] + 
                       credit['AMT_DRAWINGS_POS_CURRENT'] + 
                       credit['AMT_DRAWINGS_OTHER_CURRENT'])) > 1e-6)

    # Calculate the remaining value
    remaining_value = credit.loc[condition2, 'AMT_DRAWINGS_CURRENT'] - credit.loc[condition2, col]

    # Assign value to the columns where amount is 0
    credit.loc[condition2, [c for c in ['AMT_DRAWINGS_ATM_CURRENT', 'AMT_DRAWINGS_POS_CURRENT', 'AMT_DRAWINGS_OTHER_CURRENT'] if c != col]] = \
        np.tile((remaining_value / 2).to_numpy(), (2, 1)).T

In [ ]:
# Example for checking
credit[(credit['SK_ID_PREV'] == 2517598) & (credit['MONTHS_BALANCE'] == -18)]

,SK_ID_PREV,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECEIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
92443,2517598,-18,140522.4,135000,23625.0,59985.405,23625.0,12735.405,3909.24,3915.0,3915.0,134255.115,140522.4,140522.4,0.0,4,0.0,4.0,2.0,Active,0,0,91007

In [ ]:
# Check the existence of another case
credit[(credit['AMT_DRAWINGS_CURRENT'] > 0) & (credit['AMT_DRAWINGS_ATM_CURRENT'] > 0) & (credit['AMT_DRAWINGS_POS_CURRENT'] > 0) & (credit['AMT_DRAWINGS_OTHER_CURRENT'] == 0) &(abs(credit['AMT_DRAWINGS_CURRENT'] - 
            (credit['AMT_DRAWINGS_ATM_CURRENT'] + 
             credit['AMT_DRAWINGS_POS_CURRENT'] + 
             credit['AMT_DRAWINGS_OTHER_CURRENT'])) > 1e-6)]

,SK_ID_PREV,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECEIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
469729,1931238,-11,11701.890,450000,13500.000,27917.730,0.0,2119.500,17605.350,402525.000,402525.000,0.000,8880.390,8880.390,2.0,4,0.0,2.0,13.0,Active,0,0,118441
758579,1918729,-12,166833.855,247500,27000.000,188642.025,0.0,144810.000,491.985,24029.010,4500.000,165105.000,166833.855,166833.855,1.0,4,0.0,3.0,75.0,Active,0,0,72059
997652,1012269,-69,122485.590,135000,4500.000,23663.250,0.0,5663.250,6750.000,9000.000,9000.000,117128.430,122105.700,122105.700,1.0,2,0.0,1.0,17.0,Active,0,0,210936
1120563,2173372,-8,93216.825,90000,900.000,15284.250,0.0,11009.250,4536.360,6844.230,6844.230,89359.425,91646.325,91646.325,1.0,6,0.0,5.0,1.0,Active,0,0,90188
1237234,2651576,-16,727.515,765000,54000.000,80711.820,0.0,21483.000,15880.320,434840.175,413361.225,0.000,4304.970,4304.970,2.0,5,0.0,3.0,3.0,Active,0,0,179521
1237255,1555578,-13,727.515,765000,54000.000,80711.820,0.0,21483.000,15880.320,434840.175,413361.225,0.000,4304.970,4304.970,2.0,5,0.0,3.0,3.0,Active,0,0,157358
1770889,1184568,-18,55.125,45000,1800.000,7081.425,0.0,4956.750,2250.000,51876.000,49298.445,0.000,531.360,531.360,2.0,7,0.0,5.0,7.0,Active,0,0,107583
2112058,2657611,-8,822.105,225000,2250.000,14619.960,0.0,10725.750,11045.070,248733.990,246483.990,822.105,822.105,822.105,1.0,2,0.0,1.0,17.0,Completed,0,0,57521
2112986,1760965,-20,0.000,450000,3150.000,7511.265,0.0,301.500,2250.000,26853.525,26853.525,0.000,0.000,0.000,1.0,2,0.0,1.0,10.0,Active,0,0,77469
2260069,1309751,-28,0.000,450000,13500.000,46262.160,0.0,28735.200,22500.000,359142.075,350301.960,0.000,0.000,0.000,1.0,6,0.0,5.0,19.0,Active,0,0,131424
2550658,2643374,-14,435498.120,450000,101250.000,117312.750,0.0,2562.750,22164.345,22500.000,22500.000,422440.920,434377.620,434377.620,4.0,6,0.0,2.0,24.0,Active,0,0,141035
2622286,2188319,-13,7054.560,225000,2250.000,19288.215,0.0,2016.450,11449.980,247500.000,247500.000,0.000,3372.345,3372.345,4.0,9,0.0,5.0,14.0,Active,0,0,145540
2684680,2823413,-18,1345.500,450000,4500.000,9967.050,0.0,4117.500,2250.000,290047.140,290047.140,0.000,0.000,0.000,1.0,3,0.0,2.0,11.0,Active,0,0,72775
2743094,1111929,-21,230495.535,225000,22045.455,166942.710,0.0,137533.680,3091.005,4500.000,4500.000,224263.215,229150.035,229150.035,1.0,5,0.0,4.0,2.0,Active,0,0,71565
2745616,1993881,-22,203575.635,180000,171000.000,175180.995,0.0,4022.190,2250.000,9000.000,9000.000,173064.015,176665.635,176665.635,20.0,24,0.0,4.0,5.0,Active,0,0,237079
2885906,2287961,-23,445010.400,450000,90000.000,161717.625,0.0,56263.320,22322.970,81000.000,81000.000,437176.935,445140.900,445140.900,1.0,6,0.0,5.0,9.0,Active,0,0,213069
2890064,2344850,-21,8284.500,900000,45000.000,218816.370,0.0,52316.370,2250.000,224051.400,224051.400,5559.975,6939.000,6939.000,1.0,6,0.0,5.0,2.0,Active,0,0,186511
2991704,2487483,-5,0.000,360000,4500.000,5623.155,0.0,357.480,18675.225,370438.335,368188.335,0.000,0.000,0.000,1.0,3,0.0,2.0,9.0,Active,0,0,165188
2999655,1761932,-2,1417.410,135000,4500.000,107667.225,0.0,100832.805,2250.000,122848.560,122691.780,0.000,0.000,0.000,1.0,10,0.0,9.0,6.0,Active,0,0,29071
3025042,2273701,-3,0.000,450000,3150.000,5908.770,0.0,2569.500,23009.040,483522.885,481272.885,0.000,0.000,0.000,1.0,4,0.0,3.0,19.0,Active,0,0,265769
3030999,1003117,-7,798.255,585000,45000.000,53687.385,0.0,7888.005,6271.740,134122.500,134122.500,0.000,798.255,798.255,2.0,3,0.0,1.0,12.0,Active,0,0,75374
3038260,1540953,-3,2005.695,180000,18000.000,50429.250,0.0,5429.250,2382.660,100131.750,100131.750,0.000,0.000,0.000,1.0,2,0.0,1.0,1.0,Active,0,0,136761
3098824,2119450,-4,0.000,45000,17550.000,26555.535,0.0,8873.280,2250.000,63026.145,60776.145,0.000,0.000,0.000,4.0,11,0.0,7.0,3.0,Active,0,0,240507
3116010,1251827,-1,1570.500,270000,10350.000,94554.990,0.0,74698.650,0.000,94014.720,94014.720,0.000,0.000,0.000,1.0,24,0.0,23.0,1.0,Active,0,0,38068
3140314,1866203,-10,581.220,180000,103500.000,167816.565,0.0,59209.515,7061.265,336375.000,328628.160,0.000,0.000,0.000,11.0,39,0.0,28.0,3.0,Active,0,0,267000
3207118,2512441,-11,1347979.500,1350000,168750.000,241863.030,0.0,64113.030,58465.890,60740.730,60740.730,1305440.145,1341252.000,1341252.000,5.0,17,0.0,12.0,3.0,Active,0,0,174313
3225133,2562391,-6,180358.695,180000,162000.000,203935.500,0.0,7645.500,0.000,34290.000,34290.000,169645.500,170935.695,170935.695,6.0,7,0.0,1.0,0.0,Active,0,0,271366

In [ ]:
# Check the existence of another case
credit[(credit['AMT_DRAWINGS_CURRENT'] > 0) & (credit['AMT_DRAWINGS_ATM_CURRENT'] == 0) & (credit['AMT_DRAWINGS_POS_CURRENT'] > 0) & (credit['AMT_DRAWINGS_OTHER_CURRENT'] > 0) &(abs(credit['AMT_DRAWINGS_CURRENT'] - 
            (credit['AMT_DRAWINGS_ATM_CURRENT'] + 
             credit['AMT_DRAWINGS_POS_CURRENT'] + 
             credit['AMT_DRAWINGS_OTHER_CURRENT'])) > 1e-6)]

,SK_ID_PREV,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECEIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
3052421,2820796,-3,0.0,675000,0.0,16661.25,9000.0,5589.585,23289.03,230535.765,228285.765,0.0,0.0,0.0,0.0,5,1.0,4.0,7.0,Active,0,0,117630

In [ ]:
# Check the existence of another case
credit[(credit['AMT_DRAWINGS_CURRENT'] > 0) & (credit['AMT_DRAWINGS_ATM_CURRENT'] > 0) & (credit['AMT_DRAWINGS_POS_CURRENT'] == 0) & (credit['AMT_DRAWINGS_OTHER_CURRENT'] > 0) &(abs(credit['AMT_DRAWINGS_CURRENT'] - 
            (credit['AMT_DRAWINGS_ATM_CURRENT'] + 
             credit['AMT_DRAWINGS_POS_CURRENT'] + 
             credit['AMT_DRAWINGS_OTHER_CURRENT'])) > 1e-6)]

,SK_ID_PREV,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECEIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
317417,2148616,-74,142488.63,135000,9000.0,144000.0,134415.0,0.0,869.265,10710.0,9720.0,133574.265,143073.63,143073.63,1.0,2,1.0,0.0,1.0,Active,0,0,199757
518484,1395125,-7,1570.50,0,94500.0,787500.0,131040.0,0.0,0.000,787500.0,787500.0,0.000,0.00,0.00,4.0,5,1.0,0.0,0.0,Active,0,0,143681

In [ ]:
# Adjust the residual values proportionally
for col1, col2, col3 in [
    ('AMT_DRAWINGS_ATM_CURRENT', 'AMT_DRAWINGS_POS_CURRENT', 'AMT_DRAWINGS_OTHER_CURRENT'),
    ('AMT_DRAWINGS_ATM_CURRENT', 'AMT_DRAWINGS_OTHER_CURRENT', 'AMT_DRAWINGS_POS_CURRENT'),
    ('AMT_DRAWINGS_POS_CURRENT', 'AMT_DRAWINGS_OTHER_CURRENT', 'AMT_DRAWINGS_ATM_CURRENT')
]:
    # Condition for each case
    condition3 = (credit['AMT_DRAWINGS_CURRENT'] > 0) & \
                 (credit[col1] > 0) & \
                 (credit[col2] > 0) & \
                 (credit[col3] == 0) & \
                 (abs(credit['AMT_DRAWINGS_CURRENT'] - 
                      (credit['AMT_DRAWINGS_ATM_CURRENT'] + 
                       credit['AMT_DRAWINGS_POS_CURRENT'] + 
                       credit['AMT_DRAWINGS_OTHER_CURRENT'])) > 1e-6)

    # Perform calculations
    credit.loc[condition3, col3] = (
        credit.loc[condition3, 'AMT_DRAWINGS_CURRENT'] - 
        credit.loc[condition3, col1] - 
        credit.loc[condition3, col2]
    )

## Cleaning COUNT Columns

In [ ]:
# The count columns follow the sum rule, no need to adjust
credit[credit['CNT_DRAWINGS_CURRENT'] != (credit['CNT_DRAWINGS_ATM_CURRENT'] + credit['CNT_DRAWINGS_OTHER_CURRENT'] + credit['CNT_DRAWINGS_POS_CURRENT'])]

Empty DataFrame
Columns: [SK_ID_PREV, MONTHS_BALANCE, AMT_BALANCE, AMT_CREDIT_LIMIT_ACTUAL, AMT_DRAWINGS_ATM_CURRENT, AMT_DRAWINGS_CURRENT, AMT_DRAWINGS_OTHER_CURRENT, AMT_DRAWINGS_POS_CURRENT, AMT_INST_MIN_REGULARITY, AMT_PAYMENT_CURRENT, AMT_PAYMENT_TOTAL_CURRENT, AMT_RECEIVABLE_PRINCIPAL, AMT_RECEIVABLE, AMT_TOTAL_RECEIVABLE, CNT_DRAWINGS_ATM_CURRENT, CNT_DRAWINGS_CURRENT, CNT_DRAWINGS_OTHER_CURRENT, CNT_DRAWINGS_POS_CURRENT, CNT_INSTALMENT_MATURE_CUM, NAME_CONTRACT_STATUS, SK_DPD, SK_DPD_DEF, SK_ID_CURR]
Index: []

## Cleaning Contract Status Column

In [ ]:
# Unique value in status column
credit.NAME_CONTRACT_STATUS.unique()

array(['Active', 'Signed', 'Completed', 'Sent proposal', 'Demand',
       'Refused', 'Approved'], dtype=object)

In [25]:
credit[credit['NAME_CONTRACT_STATUS'] == 'Completed']

,SK_ID_PREV,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECEIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
310,1441883,-3,0.0,270000,0.00,0.00,0.00,0.00,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,3.0,Completed,0,0,85482
311,1441883,-4,0.0,270000,482.88,1448.64,482.88,482.88,1159.155,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,3.0,Completed,0,0,85482
312,1441883,-2,0.0,270000,0.00,0.00,0.00,0.00,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,3.0,Completed,0,0,85482
316,1441883,-1,0.0,270000,0.00,0.00,0.00,0.00,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,3.0,Completed,0,0,85482
426,2016842,-3,0.0,0,0.00,0.00,0.00,0.00,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,2.0,Completed,0,0,280613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3227131,1797458,-2,0.0,180000,0.00,0.00,0.00,0.00,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,Completed,0,0,19531
3227193,2716904,-1,0.0,45000,0.00,0.00,0.00,0.00,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,Completed,0,0,121014
3227228,2466603,-3,0.0,90000,0.00,0.00,0.00,0.00,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,Completed,0,0,33204
3227542,2378003,-4,0.0,180000,0.00,0.00,0.00,0.00,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,Completed,0,0,286313
3227844,1463847,-1,0.0,225000,0.00,0.00,0.00,0.00,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,Completed,0,0,32545

### If the status is "Completed", AMT_RECEIVABLE_PRINCIPAL, AMT_RECEIVABLE, AMT_TOTAL_RECEIVABLE will be 0

In [ ]:
receivable_check = credit[(credit['NAME_CONTRACT_STATUS'] == 'Completed') & ((credit['AMT_RECEIVABLE_PRINCIPAL'] != 0) | (credit['AMT_RECEIVABLE'] != 0) | (credit['AMT_TOTAL_RECEIVABLE'] != 0))][['SK_ID_PREV','AMT_BALANCE','MONTHS_BALANCE','AMT_DRAWINGS_CURRENT','AMT_PAYMENT_CURRENT','AMT_RECEIVABLE_PRINCIPAL','AMT_RECEIVABLE','AMT_TOTAL_RECEIVABLE','NAME_CONTRACT_STATUS']]
receivable_check

,SK_ID_PREV,AMT_BALANCE,MONTHS_BALANCE,AMT_DRAWINGS_CURRENT,AMT_PAYMENT_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECEIVABLE,AMT_TOTAL_RECEIVABLE,NAME_CONTRACT_STATUS
17432,1389209,1779.300,-1,1779.300,0.000,1779.300,1779.300,1779.300,Completed
24694,1626396,570.060,-6,642.195,72.135,570.060,570.060,570.060,Completed
54193,1791022,1.350,-1,1.350,0.000,1.350,1.350,1.350,Completed
55674,1737128,26.370,-5,52.740,68052.555,26.370,26.370,26.370,Completed
97710,1233205,27.315,-7,27.315,0.000,27.315,27.315,27.315,Completed
...,...,...,...,...,...,...,...,...,...
3193213,2499547,24.975,-4,3613.950,11213.325,24.975,24.975,24.975,Completed
3198026,2102396,26070.570,-7,26070.570,0.000,26070.570,26070.570,26070.570,Completed
3204144,2101783,130.500,-2,130.500,0.000,130.500,130.500,130.500,Completed
3204520,1143686,1121.400,-8,1121.400,0.000,1121.400,1121.400,1121.400,Completed
3219101,1861975,1889.910,-1,1889.910,1888.650,1889.910,1889.910,1889.910,Completed

In [ ]:
receivable_check[(receivable_check['AMT_RECEIVABLE_PRINCIPAL'] == receivable_check['AMT_RECEIVABLE']) & (receivable_check['AMT_RECEIVABLE'] == receivable_check['AMT_TOTAL_RECEIVABLE'])]

,SK_ID_PREV,AMT_BALANCE,MONTHS_BALANCE,AMT_DRAWINGS_CURRENT,AMT_PAYMENT_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECEIVABLE,AMT_TOTAL_RECEIVABLE,NAME_CONTRACT_STATUS
17432,1389209,1779.300,-1,1779.300,0.000,1779.300,1779.300,1779.300,Completed
24694,1626396,570.060,-6,642.195,72.135,570.060,570.060,570.060,Completed
54193,1791022,1.350,-1,1.350,0.000,1.350,1.350,1.350,Completed
55674,1737128,26.370,-5,52.740,68052.555,26.370,26.370,26.370,Completed
97710,1233205,27.315,-7,27.315,0.000,27.315,27.315,27.315,Completed
...,...,...,...,...,...,...,...,...,...
3193213,2499547,24.975,-4,3613.950,11213.325,24.975,24.975,24.975,Completed
3198026,2102396,26070.570,-7,26070.570,0.000,26070.570,26070.570,26070.570,Completed
3204144,2101783,130.500,-2,130.500,0.000,130.500,130.500,130.500,Completed
3204520,1143686,1121.400,-8,1121.400,0.000,1121.400,1121.400,1121.400,Completed
3219101,1861975,1889.910,-1,1889.910,1888.650,1889.910,1889.910,1889.910,Completed

In [ ]:
receivable_check[(receivable_check['AMT_RECEIVABLE_PRINCIPAL'] != receivable_check['AMT_RECEIVABLE']) & (receivable_check['AMT_RECEIVABLE'] == receivable_check['AMT_TOTAL_RECEIVABLE'])]

,SK_ID_PREV,AMT_BALANCE,MONTHS_BALANCE,AMT_DRAWINGS_CURRENT,AMT_PAYMENT_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECEIVABLE,AMT_TOTAL_RECEIVABLE,NAME_CONTRACT_STATUS
312669,2671308,1239.030,-5,0.000,0.0,0.0,1239.030,1239.030,Completed
312677,2671308,1239.030,-3,0.000,0.0,0.0,1239.030,1239.030,Completed
312684,2671308,1239.030,-6,0.000,0.0,0.0,1239.030,1239.030,Completed
312686,2671308,1239.030,-2,0.000,0.0,0.0,1239.030,1239.030,Completed
312696,2671308,1239.030,-4,0.000,0.0,0.0,1239.030,1239.030,Completed
431096,2320683,261.000,-4,0.000,0.0,0.0,261.000,261.000,Completed
431106,2320683,261.000,-5,0.000,0.0,0.0,261.000,261.000,Completed
431124,2320683,261.000,-7,0.000,0.0,0.0,261.000,261.000,Completed
431146,2320683,261.000,-3,0.000,0.0,0.0,261.000,261.000,Completed
431151,2320683,261.000,-6,0.000,0.0,0.0,261.000,261.000,Completed
431153,2320683,261.000,-9,0.000,0.0,0.0,261.000,261.000,Completed
431166,2320683,261.000,-8,0.000,0.0,0.0,261.000,261.000,Completed
431184,2320683,261.000,-10,0.000,0.0,0.0,261.000,261.000,Completed
660644,1958758,225.000,-21,1634.355,0.0,0.0,225.000,225.000,Completed
2776524,2762563,993.825,-7,0.000,0.0,0.0,993.825,993.825,Completed
2776556,2762563,993.825,-5,0.000,0.0,0.0,993.825,993.825,Completed
2776557,2762563,993.825,-4,0.000,0.0,0.0,993.825,993.825,Completed
2776566,2762563,993.825,-6,0.000,0.0,0.0,993.825,993.825,Completed
2776588,2762563,993.825,-8,0.000,0.0,0.0,993.825,993.825,Completed
3149336,2586795,1828.710,-2,22500.000,22500.0,0.0,258.210,258.210,Completed
3149338,2586795,1828.710,-1,0.000,0.0,0.0,1828.710,1828.710,Completed

### AMT_RECEIVABLE_PRINCIPAL = 0 meaning that customers had paid back all the principal amount, but there are still positive values in the two remaining columns. This means that there are still some extra fee or interest that hadn't been paid. Thus, we set the contract status to be active

In [ ]:
credit.loc[(credit['NAME_CONTRACT_STATUS'] == 'Completed') & 
           ((credit['AMT_RECEIVABLE_PRINCIPAL'] != 0) | 
            (credit['AMT_RECEIVABLE'] != 0) | 
            (credit['AMT_TOTAL_RECEIVABLE'] != 0)), 
           'NAME_CONTRACT_STATUS'] = 'Active'

## Check PAYMENT columns

In [ ]:
'''
AMT_INST_MIN_REGULARITY is the minimum installment due for the current month, while AMT_PAYMENT_CURRENT and AMT_PAYMENT_TOTAL_CURRENT 
represent the total amount to pay and the total paid in the previous month, respectively. 
Thus, AMT_INST_MIN_REGULARITY is calculated as the difference between the two payment values
'''

# Adjust installment value to be the difference between the two mentioned payment values for the prior month
credit = credit.sort_values(by=['SK_ID_PREV', 'MONTHS_BALANCE'], ascending=[True, False])

credit['AMT_PAYMENT_CURRENT_PREV'] = credit.groupby('SK_ID_PREV')['AMT_PAYMENT_CURRENT'].shift(-1)
credit['AMT_PAYMENT_TOTAL_CURRENT_PREV'] = credit.groupby('SK_ID_PREV')['AMT_PAYMENT_TOTAL_CURRENT'].shift(-1)

credit['AMT_INST_MIN_REGULARITY'] = credit['AMT_PAYMENT_CURRENT_PREV'] - credit['AMT_PAYMENT_TOTAL_CURRENT_PREV']
credit = credit.drop(columns=['AMT_PAYMENT_CURRENT_PREV', 'AMT_PAYMENT_TOTAL_CURRENT_PREV'])

In [31]:
credit.fillna(value= 0, inplace= True)

### There are still some case when the minimum installment > 0 but payment values are 0, but the installment next month is 0, meaning that they had paid fully in the previous month but was recorded as 0. Thus, we set all the payment values in this case to be equal to the minimum installment

In [32]:
credit.loc[
    (credit['AMT_PAYMENT_CURRENT'] == 0) & 
    (credit['AMT_PAYMENT_TOTAL_CURRENT'] == 0) & 
    (credit['AMT_INST_MIN_REGULARITY'] != 0), 
    ['AMT_PAYMENT_CURRENT', 'AMT_PAYMENT_TOTAL_CURRENT']
] = credit['AMT_INST_MIN_REGULARITY']

In [33]:
credit.sort_values(by= ['SK_ID_PREV', 'MONTHS_BALANCE'], ascending=[True, True], inplace= True)

In [ ]:
# Check for examples
cnt_inst_check = credit[['SK_ID_PREV', 'MONTHS_BALANCE', 'AMT_INST_MIN_REGULARITY', 'AMT_PAYMENT_CURRENT', 'AMT_PAYMENT_TOTAL_CURRENT', 'CNT_INSTALMENT_MATURE_CUM']]
cnt_inst_check[cnt_inst_check['SK_ID_PREV'] == 1000096].head(50)

,SK_ID_PREV,MONTHS_BALANCE,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,CNT_INSTALMENT_MATURE_CUM
1951266,1000096,-96,0.000,9000.000,9000.000,7.0
1951229,1000096,-95,0.000,9000.000,9000.000,8.0
1951286,1000096,-94,0.000,9000.000,9000.000,9.0
1951247,1000096,-93,0.000,9000.000,9000.000,10.0
1951285,1000096,-92,0.000,148500.000,148500.000,11.0
1951279,1000096,-91,0.000,9000.000,9000.000,12.0
1951253,1000096,-90,0.000,9000.000,9000.000,13.0
1951262,1000096,-89,0.000,9000.000,9000.000,14.0
1951256,1000096,-88,0.000,9000.000,9000.000,15.0
1951280,1000096,-87,0.000,9000.000,9000.000,16.0
1951278,1000096,-86,0.000,9000.000,9000.000,17.0
1951265,1000096,-85,0.000,9000.000,9000.000,18.0
1951258,1000096,-84,0.000,75150.000,75150.000,19.0
1951298,1000096,-83,0.000,130500.000,130500.000,20.0
1951282,1000096,-82,0.000,5090.805,0.000,21.0
1951270,1000096,-81,5090.805,2287.440,0.000,21.0
1951313,1000096,-80,2287.440,2287.440,0.000,21.0
1951235,1000096,-79,2287.440,2287.440,0.000,21.0
1951245,1000096,-78,2287.440,2287.440,0.000,21.0
1951248,1000096,-77,2287.440,9000.000,9000.000,22.0
1951317,1000096,-76,0.000,9000.000,9000.000,23.0
1951314,1000096,-75,0.000,9000.000,9000.000,24.0
1951281,1000096,-74,0.000,9000.000,9000.000,25.0
1951263,1000096,-73,0.000,9000.000,9000.000,26.0
1951227,1000096,-72,0.000,9000.000,9000.000,27.0
1951289,1000096,-71,0.000,9000.000,9000.000,28.0
1951231,1000096,-70,0.000,9000.000,9000.000,29.0
1951249,1000096,-69,0.000,9000.000,9000.000,30.0
1951241,1000096,-68,0.000,9000.000,9000.000,31.0
1951316,1000096,-67,0.000,9000.000,9000.000,32.0
1951307,1000096,-66,0.000,9000.000,9000.000,33.0
1951297,1000096,-65,0.000,9000.000,9000.000,34.0
1951233,1000096,-64,0.000,148184.865,148184.865,35.0
1951271,1000096,-63,0.000,11642.850,11642.850,36.0
1951267,1000096,-62,0.000,1242.855,1125.000,37.0
1951302,1000096,-61,117.855,21.960,0.000,38.0
1951234,1000096,-60,21.960,67.500,67.500,39.0
1951277,1000096,-59,0.000,0.000,0.000,40.0
1951309,1000096,-58,0.000,117.000,117.000,41.0
1951318,1000096,-57,0.000,135.000,135.000,42.0
1951250,1000096,-56,0.000,3.960,0.000,42.0
1951305,1000096,-55,3.960,3.960,0.000,42.0
1951230,1000096,-54,3.960,3.960,0.000,42.0
1951260,1000096,-53,3.960,3.960,0.000,42.0
1951252,1000096,-52,3.960,3.960,0.000,42.0
1951319,1000096,-51,3.960,3.960,0.000,42.0
1951295,1000096,-50,3.960,3.960,0.000,42.0
1951272,1000096,-49,3.960,3.960,0.000,42.0
1951292,1000096,-48,3.960,3.960,0.000,42.0
1951257,1000096,-47,3.960,3.960,0.000,42.0

### As we can see, some rows in the CNT_INSTALLMENT_MATURE_CUM column doesn't follow the rule that if the payment was made, the count would increase but if not, the count would stay as the previous month. So we adjust this problem

In [35]:
def adjust_cnt_installment(df):
    first_values = df.groupby('SK_ID_PREV')['CNT_INSTALMENT_MATURE_CUM'].transform('first')
    non_zero_payment = df['AMT_PAYMENT_TOTAL_CURRENT'] != 0
    cumulative_addition = non_zero_payment.groupby(df['SK_ID_PREV']).cumsum()
    df['CNT_INSTALMENT_MATURE_CUM'] = first_values + (cumulative_addition - cumulative_addition.groupby(df['SK_ID_PREV']).transform('first'))
    
    return df

credit = adjust_cnt_installment(credit)

In [ ]:
# Check for the example again, now this column follows the rule correctly
credit[credit['SK_ID_PREV'] == 1000096][['SK_ID_PREV', 'MONTHS_BALANCE', 'AMT_INST_MIN_REGULARITY', 'AMT_PAYMENT_CURRENT', 'AMT_PAYMENT_TOTAL_CURRENT', 'CNT_INSTALMENT_MATURE_CUM']].head(50)

,SK_ID_PREV,MONTHS_BALANCE,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,CNT_INSTALMENT_MATURE_CUM
1951266,1000096,-96,0.000,9000.000,9000.000,7.0
1951229,1000096,-95,0.000,9000.000,9000.000,8.0
1951286,1000096,-94,0.000,9000.000,9000.000,9.0
1951247,1000096,-93,0.000,9000.000,9000.000,10.0
1951285,1000096,-92,0.000,148500.000,148500.000,11.0
1951279,1000096,-91,0.000,9000.000,9000.000,12.0
1951253,1000096,-90,0.000,9000.000,9000.000,13.0
1951262,1000096,-89,0.000,9000.000,9000.000,14.0
1951256,1000096,-88,0.000,9000.000,9000.000,15.0
1951280,1000096,-87,0.000,9000.000,9000.000,16.0
1951278,1000096,-86,0.000,9000.000,9000.000,17.0
1951265,1000096,-85,0.000,9000.000,9000.000,18.0
1951258,1000096,-84,0.000,75150.000,75150.000,19.0
1951298,1000096,-83,0.000,130500.000,130500.000,20.0
1951282,1000096,-82,0.000,5090.805,0.000,20.0
1951270,1000096,-81,5090.805,2287.440,0.000,20.0
1951313,1000096,-80,2287.440,2287.440,0.000,20.0
1951235,1000096,-79,2287.440,2287.440,0.000,20.0
1951245,1000096,-78,2287.440,2287.440,0.000,20.0
1951248,1000096,-77,2287.440,9000.000,9000.000,21.0
1951317,1000096,-76,0.000,9000.000,9000.000,22.0
1951314,1000096,-75,0.000,9000.000,9000.000,23.0
1951281,1000096,-74,0.000,9000.000,9000.000,24.0
1951263,1000096,-73,0.000,9000.000,9000.000,25.0
1951227,1000096,-72,0.000,9000.000,9000.000,26.0
1951289,1000096,-71,0.000,9000.000,9000.000,27.0
1951231,1000096,-70,0.000,9000.000,9000.000,28.0
1951249,1000096,-69,0.000,9000.000,9000.000,29.0
1951241,1000096,-68,0.000,9000.000,9000.000,30.0
1951316,1000096,-67,0.000,9000.000,9000.000,31.0
1951307,1000096,-66,0.000,9000.000,9000.000,32.0
1951297,1000096,-65,0.000,9000.000,9000.000,33.0
1951233,1000096,-64,0.000,148184.865,148184.865,34.0
1951271,1000096,-63,0.000,11642.850,11642.850,35.0
1951267,1000096,-62,0.000,1242.855,1125.000,36.0
1951302,1000096,-61,117.855,21.960,0.000,36.0
1951234,1000096,-60,21.960,67.500,67.500,37.0
1951277,1000096,-59,0.000,0.000,0.000,37.0
1951309,1000096,-58,0.000,117.000,117.000,38.0
1951318,1000096,-57,0.000,135.000,135.000,39.0
1951250,1000096,-56,0.000,3.960,0.000,39.0
1951305,1000096,-55,3.960,3.960,0.000,39.0
1951230,1000096,-54,3.960,3.960,0.000,39.0
1951260,1000096,-53,3.960,3.960,0.000,39.0
1951252,1000096,-52,3.960,3.960,0.000,39.0
1951319,1000096,-51,3.960,3.960,0.000,39.0
1951295,1000096,-50,3.960,3.960,0.000,39.0
1951272,1000096,-49,3.960,3.960,0.000,39.0
1951292,1000096,-48,3.960,3.960,0.000,39.0
1951257,1000096,-47,3.960,3.960,0.000,39.0

In [ ]:
# Export cleaned dataset
credit.to_csv(r'C:\Users\Admin\Desktop\Final data prep\cleaned_data\credit_card_balance.csv')